version: "3.2"
services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: "authenticator"
      POSTGRES_USER: "authenticator"
      POSTGRES_PASSWORD: "authenticator"
    ports:
      - "5433:5432"
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "7001:6379"

networks:
  rabbitmq_go_net:
    driver: bridge
